server:
  servlet:
    context-path: /office-digital/api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/officedigitaldb?currentSchema=office-digital}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASS:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: SpringBootJPAHikariCP
      minimumIdle: 15
      maximumPoolSize: 50
      connectionTimeout: 30000
      idleTimeout: 30000
  jpa:
    properties:
      hibernate:
        default_schema: office-digital
  flyway:
    schemas: office-digital
    default-schema: office-digital

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    br.com.joaohlira: ${LOG_LEVEL:DEBUG}